/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as NovaExplodedRouteImport } from './routes/nova-exploded'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as ElekkiRouteImport } from './routes/elekki'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaExplodedRoute = NovaExplodedRouteImport.update({
  id: '/nova-exploded',
  path: '/nova-exploded',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ElekkiRoute = ElekkiRouteImport.update({
  id: '/elekki',
  path: '/elekki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elekki': typeof ElekkiRoute
  '/nova': typeof NovaRoute
  '/nova-exploded': typeof NovaExplodedRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elekki': typeof ElekkiRoute
  '/nova': typeof NovaRoute
  '/nova-exploded': typeof NovaExplodedRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elekki': typeof ElekkiRoute
  '/nova': typeof NovaRoute
  '/nova-exploded': typeof NovaExplodedRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elekki' | '/nova' | '/nova-exploded' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elekki' | '/nova' | '/nova-exploded' | '/team'
  id: '__root__' | '/' | '/elekki' | '/nova' | '/nova-exploded' | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElekkiRoute: typeof ElekkiRoute
  NovaRoute: typeof NovaRoute
  NovaExplodedRoute: typeof NovaExplodedRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-exploded': {
      id: '/nova-exploded'
      path: '/nova-exploded'
      fullPath: '/nova-exploded'
      preLoaderRoute: typeof NovaExplodedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elekki': {
      id: '/elekki'
      path: '/elekki'
      fullPath: '/elekki'
      preLoaderRoute: typeof ElekkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElekkiRoute: ElekkiRoute,
  NovaRoute: NovaRoute,
  NovaExplodedRoute: NovaExplodedRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
